name: Deploy Site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy react app to github pages 🚀
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
