name: Deploy Site
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run : yarn install --frozen-lockfile # install deps
        shell: bash
      - run : yarn build # build the site
        shell: bash
      - run : git config user.name github-actions
        shell: bash
      - run : git config user.email github-actions@github.com
        shell: bash
      - run : git add docs -f
        shell: bash
      - run : git commit -m "Deploy :rocket:"
        shell: bash
      - run : git push origin HEAD:gh-pages --force
        shell: bash
